[creagen-editor]
path = "~/p/creagen-editor"
repo = "git@github.com:Lyr-7d1h/creagen-editor.git"
update = true

[creagen-generations]
path = "~/p/creagen-generations"
repo = "git@github.com:Lyr-7d1h/creagen-generations.git"
update = true

[creagen-deployment]
path = "~/p/creagen-deployment"
repo = "git@github.com:Lyr-7d1h/creagen-cloudflare.git"
update = true

[creagen]
path = "~/p/creagen"
repo = "git@github.com:Lyr-7d1h/creagen.git"
execnow = "code ~/p/creagen ~/p/creagen-editor ~/p/creagen-generations ~/p/creagen-deployment"
update= true
[[creagen.windows]]
name = "live"
[[creagen.windows.panes]]
exec = ["npm i", "npm run watch"]
[[creagen.windows.panes]]
cwd = "~/p/creagen-editor"
split = "horizontal"
exec = [
	"npm i", 
	"CREAGEN_EDITOR_CONTROLLER_URL=http://localhost:8787 npm start"
]
[[creagen.windows]]
name = "vcs"
[[creagen.windows.panes]]
cwd = "~/p/creagen-editor"
exec = ["watch --color jj --ignore-working-copy log --color=always"]
[[creagen.windows.panes]]
cwd = "~/p/creagen-editor"
exec = [""]
[[creagen.windows]]
name = "deployment"
[[creagen.windows.panes]]
exec = [
	"npm i", 
	"CREAGEN_EDITOR_CONTROLLER_URL=http://localhost:8787 npm start"
]
[[creagen.windows.panes]]
exec = ""
[[creagen.windows]]
name = "generations"
cwd = "~/p/creagen-generations"
