[creagen-editor]
path = "~/p/creagen-editor"
repo = "git@github.com:Lyr-7d1h/creagen-editor.git"
update = true

[creagen-generations]
path = "~/p/creagen-generations"
repo = "git@github.com:Lyr-7d1h/creagen-generations.git"
update = true

[creagen-deployment]
path = "~/p/creagen-deployment"
repo = "git@github.com:Lyr-7d1h/creagen-cloudflare.git"
update = true

[creagen]
path = "~/p/creagen"
repo = "git@github.com:Lyr-7d1h/creagen.git"
execnow = "code ~/p/creagen ~/p/creagen-editor ~/p/creagen-generations"
update= true
[[creagen.windows]]
name = "app"
[[creagen.windows.panes]]
exec = ""
[[creagen.windows.panes]]
exec = ["npm i", "npm run watch"]
size = 90
[[creagen.windows.panes]]
cwd = "~/p/creagen-editor"
split = "horizontal"
exec = ["npm i", "npm start"]
[[creagen.windows]]
name = "generations"
cwd = "~/p/creagen-generations"
